name: Update Problem Metrics

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Count Problems in Each Folder
        run: |
          echo "## 📊 Problem-Solving Metrics" > README.md
          echo "" >> README.md

          # Check if the "solved" folder exists
          if [ -d "Solved" ]; then
          for dir in Solved/*/; do
              count=$(find "$dir" -type f | wc -l)
              folder_name=$(basename "$dir")
              echo "- **${folder_name}**: $count problems solved" >> README.md
          done
          else
          echo "No solved problems found." >> README.md
          fi

          echo "" >> README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated problem-solving metrics"
          git push
